name: ayimoloumap_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  google_maps_flutter: ^2.3.0
  geolocator: ^10.0.0
  flutter_polyline_points: ^3.1.0
  http: ^1.1.0
  provider: ^6.1.5+1
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # <--- ajouté ici

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0000FF"
  min_sdk_android: 21   # optionnel mais recommandé

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/pin.png
